type(false)
type(true)

nome_1 = 'maria'
idade_1 = 3

nome_2 = 'ana'
idade_2 = 23

nome_3 = 'maria'
idade_3 = 45

nome_1 == nome_3  #true
nome_1 != nome_2 #true
nome_1 == nome_3 and idade_1 == idade_3 #false
nome_1 == nome_3 or idade_1 == idade_3 #true
true and not false #true


'''
1 == 1.0 true mesmo que seja um int e um float
os objetos têm o mesmo hash?

1 is 1.0 false
os objetos são o mesmo objeto?

++conectivos lógicos
and, or, not
and: true and true -> true
or: not false -> true
not: false and true -> false
'''
